// Code generated by goctl. DO NOT EDIT.
package types

type GroupSendResp struct {
	List []SendResp
}

type Item struct {
	To   string `json:"to"`
	Vars string `json:"vars"`
}

type SendReq struct {
	AppId   int64  `json:"appid"`
	To      string `json:"to"`
	Content string `json:"content"`
	Secret  string `json:"secret"`
}

type SendResp struct {
	Status string `json:"status"`
	SendId string `json:"send_id"`
	Fee    int32  `json:"fee"`
}

type XsendReq struct {
	AppId   int64  `json:"appid"`
	To      string `json:"to"`
	Secret  string `json:"secret"`
	Project string `json:"project"`
}

type GroupSendReq struct {
	AppId   int64  `json:"appid"`
	Content string `json:"content"`
	Secret  string `json:"secret"`
	Params  []Item `json:"param"`
}

type GroupXsendReq struct {
	AppId   int64  `json:"appid"`
	Secret  string `json:"secret"`
	Project string `json:"project"`
	Params  []Item `json:"param"`
}

type Req struct {
}

type StatusResp struct {
	Status  string `json:"status"`
	Runtime int64  `json:"runtime"`
}

type TimestampResp struct {
	Timestamp int64 `json:"timestamp"`
}
