// Code generated by goctl. DO NOT EDIT.
package types

type SendReq struct {
	AppID   int    `json:"appid"`
	Secret  string `json:"secret"`
	To      string `json:"to"`
	Content string `json:"content"`
}

type SendResp struct {
	Credit   int `json:"credit"`
	Faild    int `json:"faild"`
	Successd int `json:"successd"`
}
