// Code generated by goctl. DO NOT EDIT.
package types

type SendReq struct {
	AppID   int    `json:"appid"`
	Secret  string `json:"secret"`
	To      string `json:"to"`
	Content string `json:"content"`
}

type SendResp struct {
	Id       int64  `json:"id"`
	Name     string `json:"name"`
	Token    string `json:"token"`
	ExpireAt string `json:"expireAt"`
}
