// Code generated by goctl. DO NOT EDIT.
// Source: appsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/appsvc/internal/logic/appsvc"
	"github.com/aheadIV/NightVoyager/appsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/appsvc/types/appsvc"
)

type AppsvcServer struct {
	svcCtx *svc.ServiceContext
	appsvc.UnimplementedAppsvcServer
}

func NewAppsvcServer(svcCtx *svc.ServiceContext) *AppsvcServer {
	return &AppsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AppsvcServer) GetAppById(ctx context.Context, in *appsvc.GetAppByIdReq) (*appsvc.GetAppByIdResp, error) {
	l := appsvclogic.NewGetAppByIdLogic(ctx, s.svcCtx)
	return l.GetAppById(in)
}

func (s *AppsvcServer) CreateApp(ctx context.Context, in *appsvc.CreateAppReq) (*appsvc.CreateAppResp, error) {
	l := appsvclogic.NewCreateAppLogic(ctx, s.svcCtx)
	return l.CreateApp(in)
}

func (s *AppsvcServer) AppList(ctx context.Context, in *appsvc.AppListReq) (*appsvc.AppListResp, error) {
	l := appsvclogic.NewAppListLogic(ctx, s.svcCtx)
	return l.AppList(in)
}
