// Code generated by goctl. DO NOT EDIT.
// Source: sendsvc.proto

package tplsendsvc

import (
	"context"

	"github.com/aheadIV/NightVoyager/sendsvc/types/sendsvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRecReq   = sendsvc.CreateRecReq
	CreateRecResp  = sendsvc.CreateRecResp
	CreateSigReq   = sendsvc.CreateSigReq
	CreateSigResp  = sendsvc.CreateSigResp
	CreateTplReq   = sendsvc.CreateTplReq
	CreateTplResp  = sendsvc.CreateTplResp
	DeletTplResp   = sendsvc.DeletTplResp
	DeleteSigReq   = sendsvc.DeleteSigReq
	DeleteSigResp  = sendsvc.DeleteSigResp
	DeleteTplReq   = sendsvc.DeleteTplReq
	GetRecByIdReq  = sendsvc.GetRecByIdReq
	GetRecByIdResp = sendsvc.GetRecByIdResp
	GetSigByIdReq  = sendsvc.GetSigByIdReq
	GetSigByIdResp = sendsvc.GetSigByIdResp
	GetTplByIdReq  = sendsvc.GetTplByIdReq
	GetTplByIdResp = sendsvc.GetTplByIdResp
	Rec            = sendsvc.Rec
	SigListReq     = sendsvc.SigListReq
	SigListResp    = sendsvc.SigListResp
	Sign           = sendsvc.Sign
	Tpl            = sendsvc.Tpl
	TplListReq     = sendsvc.TplListReq
	TplListResp    = sendsvc.TplListResp
	UpdateSigReq   = sendsvc.UpdateSigReq
	UpdateSigResp  = sendsvc.UpdateSigResp
	UpdateTplReq   = sendsvc.UpdateTplReq
	UpdateTplResp  = sendsvc.UpdateTplResp

	TplSendSvc interface {
		CreateRec(ctx context.Context, in *CreateRecReq, opts ...grpc.CallOption) (*CreateRecResp, error)
		GetRecById(ctx context.Context, in *GetRecByIdReq, opts ...grpc.CallOption) (*GetRecByIdResp, error)
	}

	defaultTplSendSvc struct {
		cli zrpc.Client
	}
)

func NewTplSendSvc(cli zrpc.Client) TplSendSvc {
	return &defaultTplSendSvc{
		cli: cli,
	}
}

func (m *defaultTplSendSvc) CreateRec(ctx context.Context, in *CreateRecReq, opts ...grpc.CallOption) (*CreateRecResp, error) {
	client := sendsvc.NewTplSendSvcClient(m.cli.Conn())
	return client.CreateRec(ctx, in, opts...)
}

func (m *defaultTplSendSvc) GetRecById(ctx context.Context, in *GetRecByIdReq, opts ...grpc.CallOption) (*GetRecByIdResp, error) {
	client := sendsvc.NewTplSendSvcClient(m.cli.Conn())
	return client.GetRecById(ctx, in, opts...)
}
