// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	globalsms "github.com/aheadIV/NightVoyager/send/internal/handler/globalsms"
	service "github.com/aheadIV/NightVoyager/send/internal/handler/service"
	"github.com/aheadIV/NightVoyager/send/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: globalsms.SendHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/xsend",
				Handler: globalsms.SendTplHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/send",
				Handler: globalsms.SendGroupHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/group/xsend",
				Handler: globalsms.SendGroupTplHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(1048576),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/status",
				Handler: service.StatusHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/timestamp",
				Handler: service.TimestampHandler(serverCtx),
			},
		},
		rest.WithPrefix("/v1"),
		rest.WithMaxBytes(1048576),
	)
}
