// Code generated by goctl. DO NOT EDIT.
// Source: accountsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/accountsvc/internal/logic/accountsvc"
	"github.com/aheadIV/NightVoyager/accountsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/accountsvc/types/accountsvc"
)

type AccountSvcServer struct {
	svcCtx *svc.ServiceContext
	accountsvc.UnimplementedAccountSvcServer
}

func NewAccountSvcServer(svcCtx *svc.ServiceContext) *AccountSvcServer {
	return &AccountSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountSvcServer) GetByAccount(ctx context.Context, in *accountsvc.GetByAccountReq) (*accountsvc.GetByAccountResp, error) {
	l := accountsvclogic.NewGetByAccountLogic(ctx, s.svcCtx)
	return l.GetByAccount(in)
}

func (s *AccountSvcServer) GetById(ctx context.Context, in *accountsvc.GetByIdReq) (*accountsvc.GetByIdResp, error) {
	l := accountsvclogic.NewGetByIdLogic(ctx, s.svcCtx)
	return l.GetById(in)
}

func (s *AccountSvcServer) Create(ctx context.Context, in *accountsvc.CreateReq) (*accountsvc.CreateResp, error) {
	l := accountsvclogic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *AccountSvcServer) Update(ctx context.Context, in *accountsvc.UpdateReq) (*accountsvc.UpdateResp, error) {
	l := accountsvclogic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *AccountSvcServer) Delete(ctx context.Context, in *accountsvc.DeleteReq) (*accountsvc.DeleteResp, error) {
	l := accountsvclogic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
