// Code generated by goctl. DO NOT EDIT.
// Source: appsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/appsvc/internal/logic/sendlogsvc"
	"github.com/aheadIV/NightVoyager/appsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/appsvc/types/appsvc"
)

type SendLogsvcServer struct {
	svcCtx *svc.ServiceContext
	appsvc.UnimplementedSendLogsvcServer
}

func NewSendLogsvcServer(svcCtx *svc.ServiceContext) *SendLogsvcServer {
	return &SendLogsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *SendLogsvcServer) InsertLog(ctx context.Context, in *appsvc.Req) (*appsvc.Resp, error) {
	l := sendlogsvclogic.NewInsertLogLogic(ctx, s.svcCtx)
	return l.InsertLog(in)
}

func (s *SendLogsvcServer) SendLogList(ctx context.Context, in *appsvc.Req) (*appsvc.Resp, error) {
	l := sendlogsvclogic.NewSendLogListLogic(ctx, s.svcCtx)
	return l.SendLogList(in)
}
