// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.25.1
// source: templatesvc.proto

package templatesvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TemplatesvcClient is the client API for Templatesvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TemplatesvcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type templatesvcClient struct {
	cc grpc.ClientConnInterface
}

func NewTemplatesvcClient(cc grpc.ClientConnInterface) TemplatesvcClient {
	return &templatesvcClient{cc}
}

func (c *templatesvcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, "/templatesvc.Templatesvc/Ping", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TemplatesvcServer is the server API for Templatesvc service.
// All implementations must embed UnimplementedTemplatesvcServer
// for forward compatibility
type TemplatesvcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedTemplatesvcServer()
}

// UnimplementedTemplatesvcServer must be embedded to have forward compatible implementations.
type UnimplementedTemplatesvcServer struct {
}

func (UnimplementedTemplatesvcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedTemplatesvcServer) mustEmbedUnimplementedTemplatesvcServer() {}

// UnsafeTemplatesvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TemplatesvcServer will
// result in compilation errors.
type UnsafeTemplatesvcServer interface {
	mustEmbedUnimplementedTemplatesvcServer()
}

func RegisterTemplatesvcServer(s grpc.ServiceRegistrar, srv TemplatesvcServer) {
	s.RegisterService(&Templatesvc_ServiceDesc, srv)
}

func _Templatesvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TemplatesvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/templatesvc.Templatesvc/Ping",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TemplatesvcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Templatesvc_ServiceDesc is the grpc.ServiceDesc for Templatesvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Templatesvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "templatesvc.Templatesvc",
	HandlerType: (*TemplatesvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Templatesvc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "templatesvc.proto",
}
