// Code generated by goctl. DO NOT EDIT.
// Source: sendsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/sendsvc/internal/logic/tplsignsvc"
	"github.com/aheadIV/NightVoyager/sendsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/sendsvc/types/sendsvc"
)

type TplSignSvcServer struct {
	svcCtx *svc.ServiceContext
	sendsvc.UnimplementedTplSignSvcServer
}

func NewTplSignSvcServer(svcCtx *svc.ServiceContext) *TplSignSvcServer {
	return &TplSignSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *TplSignSvcServer) GetSigById(ctx context.Context, in *sendsvc.GetSigByIdReq) (*sendsvc.GetSigByIdResp, error) {
	l := tplsignsvclogic.NewGetSigByIdLogic(ctx, s.svcCtx)
	return l.GetSigById(in)
}

func (s *TplSignSvcServer) CreateSig(ctx context.Context, in *sendsvc.CreateSigReq) (*sendsvc.CreateSigResp, error) {
	l := tplsignsvclogic.NewCreateSigLogic(ctx, s.svcCtx)
	return l.CreateSig(in)
}

func (s *TplSignSvcServer) UpdateSig(ctx context.Context, in *sendsvc.UpdateSigReq) (*sendsvc.UpdateSigResp, error) {
	l := tplsignsvclogic.NewUpdateSigLogic(ctx, s.svcCtx)
	return l.UpdateSig(in)
}

func (s *TplSignSvcServer) DeleteSig(ctx context.Context, in *sendsvc.DeleteSigReq) (*sendsvc.DeleteSigResp, error) {
	l := tplsignsvclogic.NewDeleteSigLogic(ctx, s.svcCtx)
	return l.DeleteSig(in)
}

func (s *TplSignSvcServer) SigList(ctx context.Context, in *sendsvc.SigListReq) (*sendsvc.SigListResp, error) {
	l := tplsignsvclogic.NewSigListLogic(ctx, s.svcCtx)
	return l.SigList(in)
}
