// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.0
// source: tplsvc.proto

package tplsvc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Tpl struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	TplName    string `protobuf:"bytes,2,opt,name=tpl_name,json=tplName,proto3" json:"tpl_name,omitempty"`
	TplContent string `protobuf:"bytes,3,opt,name=tpl_content,json=tplContent,proto3" json:"tpl_content,omitempty"`
	TplType    string `protobuf:"bytes,4,opt,name=tpl_type,json=tplType,proto3" json:"tpl_type,omitempty"`
	SignId     int64  `protobuf:"varint,5,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	AccountId  int64  `protobuf:"varint,6,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status     int64  `protobuf:"varint,7,opt,name=status,proto3" json:"status,omitempty"`
	Remark     string `protobuf:"bytes,8,opt,name=remark,proto3" json:"remark,omitempty"`
	CreatedAt  int64  `protobuf:"varint,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt  int64  `protobuf:"varint,10,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Tpl) Reset() {
	*x = Tpl{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Tpl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tpl) ProtoMessage() {}

func (x *Tpl) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tpl.ProtoReflect.Descriptor instead.
func (*Tpl) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{0}
}

func (x *Tpl) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Tpl) GetTplName() string {
	if x != nil {
		return x.TplName
	}
	return ""
}

func (x *Tpl) GetTplContent() string {
	if x != nil {
		return x.TplContent
	}
	return ""
}

func (x *Tpl) GetTplType() string {
	if x != nil {
		return x.TplType
	}
	return ""
}

func (x *Tpl) GetSignId() int64 {
	if x != nil {
		return x.SignId
	}
	return 0
}

func (x *Tpl) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *Tpl) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Tpl) GetRemark() string {
	if x != nil {
		return x.Remark
	}
	return ""
}

func (x *Tpl) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Tpl) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetTplByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetTplByIdReq) Reset() {
	*x = GetTplByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTplByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTplByIdReq) ProtoMessage() {}

func (x *GetTplByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTplByIdReq.ProtoReflect.Descriptor instead.
func (*GetTplByIdReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{1}
}

func (x *GetTplByIdReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetTplByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Tpl   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetTplByIdResp) Reset() {
	*x = GetTplByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetTplByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTplByIdResp) ProtoMessage() {}

func (x *GetTplByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTplByIdResp.ProtoReflect.Descriptor instead.
func (*GetTplByIdResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{2}
}

func (x *GetTplByIdResp) GetItem() *Tpl {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetTplByIdResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type CreateTplReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignId    int64  `protobuf:"varint,1,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	AccountId int64  `protobuf:"varint,2,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Content   string `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
}

func (x *CreateTplReq) Reset() {
	*x = CreateTplReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTplReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTplReq) ProtoMessage() {}

func (x *CreateTplReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTplReq.ProtoReflect.Descriptor instead.
func (*CreateTplReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{3}
}

func (x *CreateTplReq) GetSignId() int64 {
	if x != nil {
		return x.SignId
	}
	return 0
}

func (x *CreateTplReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateTplReq) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

type CreateTplResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TplId string `protobuf:"bytes,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *CreateTplResp) Reset() {
	*x = CreateTplResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateTplResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTplResp) ProtoMessage() {}

func (x *CreateTplResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTplResp.ProtoReflect.Descriptor instead.
func (*CreateTplResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{4}
}

func (x *CreateTplResp) GetTplId() string {
	if x != nil {
		return x.TplId
	}
	return ""
}

func (x *CreateTplResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type TplListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId  int64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status     int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	TplContent string `protobuf:"bytes,3,opt,name=tpl_content,json=tplContent,proto3" json:"tpl_content,omitempty"`
	CreatedLt  int64  `protobuf:"varint,4,opt,name=created_lt,json=createdLt,proto3" json:"created_lt,omitempty"`
	CreatedGt  int64  `protobuf:"varint,5,opt,name=created_gt,json=createdGt,proto3" json:"created_gt,omitempty"`
	Page       int64  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize   int64  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Signature  string `protobuf:"bytes,9,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *TplListReq) Reset() {
	*x = TplListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TplListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TplListReq) ProtoMessage() {}

func (x *TplListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TplListReq.ProtoReflect.Descriptor instead.
func (*TplListReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{5}
}

func (x *TplListReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *TplListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *TplListReq) GetTplContent() string {
	if x != nil {
		return x.TplContent
	}
	return ""
}

func (x *TplListReq) GetCreatedLt() int64 {
	if x != nil {
		return x.CreatedLt
	}
	return 0
}

func (x *TplListReq) GetCreatedGt() int64 {
	if x != nil {
		return x.CreatedGt
	}
	return 0
}

func (x *TplListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *TplListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *TplListReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type TplListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Tpl `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *TplListResp) Reset() {
	*x = TplListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TplListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TplListResp) ProtoMessage() {}

func (x *TplListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TplListResp.ProtoReflect.Descriptor instead.
func (*TplListResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{6}
}

func (x *TplListResp) GetList() []*Tpl {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *TplListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateTplReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TplId      string `protobuf:"bytes,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	SignId     int64  `protobuf:"varint,2,opt,name=sign_id,json=signId,proto3" json:"sign_id,omitempty"`
	TplContent string `protobuf:"bytes,3,opt,name=tpl_content,json=tplContent,proto3" json:"tpl_content,omitempty"`
}

func (x *UpdateTplReq) Reset() {
	*x = UpdateTplReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTplReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTplReq) ProtoMessage() {}

func (x *UpdateTplReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTplReq.ProtoReflect.Descriptor instead.
func (*UpdateTplReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateTplReq) GetTplId() string {
	if x != nil {
		return x.TplId
	}
	return ""
}

func (x *UpdateTplReq) GetSignId() int64 {
	if x != nil {
		return x.SignId
	}
	return 0
}

func (x *UpdateTplReq) GetTplContent() string {
	if x != nil {
		return x.TplContent
	}
	return ""
}

type UpdateTplResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TplId string `protobuf:"bytes,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	Err   string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *UpdateTplResp) Reset() {
	*x = UpdateTplResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateTplResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateTplResp) ProtoMessage() {}

func (x *UpdateTplResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateTplResp.ProtoReflect.Descriptor instead.
func (*UpdateTplResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateTplResp) GetTplId() string {
	if x != nil {
		return x.TplId
	}
	return ""
}

func (x *UpdateTplResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type DeleteTplReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TplId string `protobuf:"bytes,1,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
}

func (x *DeleteTplReq) Reset() {
	*x = DeleteTplReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteTplReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTplReq) ProtoMessage() {}

func (x *DeleteTplReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTplReq.ProtoReflect.Descriptor instead.
func (*DeleteTplReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteTplReq) GetTplId() string {
	if x != nil {
		return x.TplId
	}
	return ""
}

type DeletTplResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Err string `protobuf:"bytes,1,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *DeletTplResp) Reset() {
	*x = DeletTplResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletTplResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletTplResp) ProtoMessage() {}

func (x *DeletTplResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletTplResp.ProtoReflect.Descriptor instead.
func (*DeletTplResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{10}
}

func (x *DeletTplResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type Sign struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Signature string `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
	IsDefault int64  `protobuf:"varint,3,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Status    int64  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt int64  `protobuf:"varint,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt int64  `protobuf:"varint,6,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Sign) Reset() {
	*x = Sign{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Sign) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Sign) ProtoMessage() {}

func (x *Sign) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Sign.ProtoReflect.Descriptor instead.
func (*Sign) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{11}
}

func (x *Sign) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Sign) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *Sign) GetIsDefault() int64 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *Sign) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Sign) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Sign) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type GetSigByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetSigByIdReq) Reset() {
	*x = GetSigByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSigByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigByIdReq) ProtoMessage() {}

func (x *GetSigByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigByIdReq.ProtoReflect.Descriptor instead.
func (*GetSigByIdReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{12}
}

func (x *GetSigByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetSigByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Sign  `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetSigByIdResp) Reset() {
	*x = GetSigByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSigByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSigByIdResp) ProtoMessage() {}

func (x *GetSigByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSigByIdResp.ProtoReflect.Descriptor instead.
func (*GetSigByIdResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{13}
}

func (x *GetSigByIdResp) GetItem() *Sign {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetSigByIdResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

type CreateSigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	IsDefault int64  `protobuf:"varint,2,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *CreateSigReq) Reset() {
	*x = CreateSigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSigReq) ProtoMessage() {}

func (x *CreateSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSigReq.ProtoReflect.Descriptor instead.
func (*CreateSigReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{14}
}

func (x *CreateSigReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *CreateSigReq) GetIsDefault() int64 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

func (x *CreateSigReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

type CreateSigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateSigResp) Reset() {
	*x = CreateSigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSigResp) ProtoMessage() {}

func (x *CreateSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSigResp.ProtoReflect.Descriptor instead.
func (*CreateSigResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{15}
}

func (x *CreateSigResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SigListReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccountId int64  `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	Status    int64  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Signature string `protobuf:"bytes,3,opt,name=signature,proto3" json:"signature,omitempty"`
	CreatedLt int64  `protobuf:"varint,4,opt,name=created_lt,json=createdLt,proto3" json:"created_lt,omitempty"`
	CreatedGt int64  `protobuf:"varint,5,opt,name=created_gt,json=createdGt,proto3" json:"created_gt,omitempty"`
	Page      int64  `protobuf:"varint,7,opt,name=page,proto3" json:"page,omitempty"`
	PageSize  int64  `protobuf:"varint,8,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	IsDefault int64  `protobuf:"varint,9,opt,name=is_default,json=isDefault,proto3" json:"is_default,omitempty"`
}

func (x *SigListReq) Reset() {
	*x = SigListReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigListReq) ProtoMessage() {}

func (x *SigListReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigListReq.ProtoReflect.Descriptor instead.
func (*SigListReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{16}
}

func (x *SigListReq) GetAccountId() int64 {
	if x != nil {
		return x.AccountId
	}
	return 0
}

func (x *SigListReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *SigListReq) GetSignature() string {
	if x != nil {
		return x.Signature
	}
	return ""
}

func (x *SigListReq) GetCreatedLt() int64 {
	if x != nil {
		return x.CreatedLt
	}
	return 0
}

func (x *SigListReq) GetCreatedGt() int64 {
	if x != nil {
		return x.CreatedGt
	}
	return 0
}

func (x *SigListReq) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *SigListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *SigListReq) GetIsDefault() int64 {
	if x != nil {
		return x.IsDefault
	}
	return 0
}

type SigListResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	List  []*Sign `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	Total int64   `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *SigListResp) Reset() {
	*x = SigListResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SigListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SigListResp) ProtoMessage() {}

func (x *SigListResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SigListResp.ProtoReflect.Descriptor instead.
func (*SigListResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{17}
}

func (x *SigListResp) GetList() []*Sign {
	if x != nil {
		return x.List
	}
	return nil
}

func (x *SigListResp) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type UpdateSigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSigReq) Reset() {
	*x = UpdateSigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSigReq) ProtoMessage() {}

func (x *UpdateSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSigReq.ProtoReflect.Descriptor instead.
func (*UpdateSigReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{18}
}

type UpdateSigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateSigResp) Reset() {
	*x = UpdateSigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSigResp) ProtoMessage() {}

func (x *UpdateSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSigResp.ProtoReflect.Descriptor instead.
func (*UpdateSigResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{19}
}

type DeleteSigReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSigReq) Reset() {
	*x = DeleteSigReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSigReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSigReq) ProtoMessage() {}

func (x *DeleteSigReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSigReq.ProtoReflect.Descriptor instead.
func (*DeleteSigReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{20}
}

type DeleteSigResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteSigResp) Reset() {
	*x = DeleteSigResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteSigResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSigResp) ProtoMessage() {}

func (x *DeleteSigResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSigResp.ProtoReflect.Descriptor instead.
func (*DeleteSigResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{21}
}

type Rec struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Mobile       string `protobuf:"bytes,2,opt,name=mobile,proto3" json:"mobile,omitempty"`
	Nationcode   string `protobuf:"bytes,3,opt,name=nationcode,proto3" json:"nationcode,omitempty"`
	AppId        int64  `protobuf:"varint,4,opt,name=app_id,json=appId,proto3" json:"app_id,omitempty"`
	TemplateType string `protobuf:"bytes,5,opt,name=template_type,json=templateType,proto3" json:"template_type,omitempty"`
	TplId        string `protobuf:"bytes,6,opt,name=tpl_id,json=tplId,proto3" json:"tpl_id,omitempty"`
	TplParam     string `protobuf:"bytes,7,opt,name=tpl_param,json=tplParam,proto3" json:"tpl_param,omitempty"`
	SendAt       string `protobuf:"bytes,8,opt,name=send_at,json=sendAt,proto3" json:"send_at,omitempty"`
	SendStatus   int64  `protobuf:"varint,9,opt,name=send_status,json=sendStatus,proto3" json:"send_status,omitempty"`
	SenderIp     string `protobuf:"bytes,10,opt,name=sender_ip,json=senderIp,proto3" json:"sender_ip,omitempty"`
	CreatedAt    int64  `protobuf:"varint,11,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt    int64  `protobuf:"varint,12,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
}

func (x *Rec) Reset() {
	*x = Rec{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Rec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Rec) ProtoMessage() {}

func (x *Rec) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Rec.ProtoReflect.Descriptor instead.
func (*Rec) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{22}
}

func (x *Rec) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Rec) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *Rec) GetNationcode() string {
	if x != nil {
		return x.Nationcode
	}
	return ""
}

func (x *Rec) GetAppId() int64 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *Rec) GetTemplateType() string {
	if x != nil {
		return x.TemplateType
	}
	return ""
}

func (x *Rec) GetTplId() string {
	if x != nil {
		return x.TplId
	}
	return ""
}

func (x *Rec) GetTplParam() string {
	if x != nil {
		return x.TplParam
	}
	return ""
}

func (x *Rec) GetSendAt() string {
	if x != nil {
		return x.SendAt
	}
	return ""
}

func (x *Rec) GetSendStatus() int64 {
	if x != nil {
		return x.SendStatus
	}
	return 0
}

func (x *Rec) GetSenderIp() string {
	if x != nil {
		return x.SenderIp
	}
	return ""
}

func (x *Rec) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Rec) GetUpdatedAt() int64 {
	if x != nil {
		return x.UpdatedAt
	}
	return 0
}

type CreateRecReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Mobile string `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
}

func (x *CreateRecReq) Reset() {
	*x = CreateRecReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecReq) ProtoMessage() {}

func (x *CreateRecReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecReq.ProtoReflect.Descriptor instead.
func (*CreateRecReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{23}
}

func (x *CreateRecReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

type CreateRecResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateRecResp) Reset() {
	*x = CreateRecResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateRecResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRecResp) ProtoMessage() {}

func (x *CreateRecResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRecResp.ProtoReflect.Descriptor instead.
func (*CreateRecResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{24}
}

func (x *CreateRecResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRecByIdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *GetRecByIdReq) Reset() {
	*x = GetRecByIdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecByIdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecByIdReq) ProtoMessage() {}

func (x *GetRecByIdReq) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecByIdReq.ProtoReflect.Descriptor instead.
func (*GetRecByIdReq) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{25}
}

func (x *GetRecByIdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetRecByIdResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Item *Rec   `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	Err  string `protobuf:"bytes,2,opt,name=err,proto3" json:"err,omitempty"`
}

func (x *GetRecByIdResp) Reset() {
	*x = GetRecByIdResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_tplsvc_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetRecByIdResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRecByIdResp) ProtoMessage() {}

func (x *GetRecByIdResp) ProtoReflect() protoreflect.Message {
	mi := &file_tplsvc_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRecByIdResp.ProtoReflect.Descriptor instead.
func (*GetRecByIdResp) Descriptor() ([]byte, []int) {
	return file_tplsvc_proto_rawDescGZIP(), []int{26}
}

func (x *GetRecByIdResp) GetItem() *Rec {
	if x != nil {
		return x.Item
	}
	return nil
}

func (x *GetRecByIdResp) GetErr() string {
	if x != nil {
		return x.Err
	}
	return ""
}

var File_tplsvc_proto protoreflect.FileDescriptor

var file_tplsvc_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06,
	0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x22, 0x92, 0x02, 0x0a, 0x03, 0x54, 0x70, 0x6c, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19,
	0x0a, 0x08, 0x74, 0x70, 0x6c, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x74, 0x70, 0x6c, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x70, 0x6c,
	0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a,
	0x74, 0x70, 0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x70,
	0x6c, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x74, 0x70,
	0x6c, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x6d, 0x61, 0x72, 0x6b, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x1f, 0x0a, 0x0d, 0x47,
	0x65, 0x74, 0x54, 0x70, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x54, 0x70, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f,
	0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74,
	0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x54, 0x70, 0x6c, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12,
	0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72,
	0x72, 0x22, 0x60, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x52, 0x65,
	0x71, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x06, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74,
	0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x70, 0x6c,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x70, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x65,
	0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0xf1, 0x01,
	0x0a, 0x0a, 0x54, 0x70, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x70, 0x6c, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x70, 0x6c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x6e, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f,
	0x6c, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x64, 0x4c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67,
	0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x47, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65,
	0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x22, 0x44, 0x0a, 0x0b, 0x54, 0x70, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x1f, 0x0a, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x54, 0x70, 0x6c, 0x52, 0x04, 0x6c, 0x69, 0x73,
	0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x22, 0x5f, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x70, 0x6c, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x69, 0x67, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x06, 0x73, 0x69, 0x67, 0x6e, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x70, 0x6c, 0x5f, 0x63,
	0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x74, 0x70,
	0x6c, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x22, 0x38, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x70, 0x6c,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64,
	0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65,
	0x72, 0x72, 0x22, 0x25, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x52,
	0x65, 0x71, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x70, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64, 0x22, 0x20, 0x0a, 0x0c, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0xa9, 0x01, 0x0a, 0x04,
	0x53, 0x69, 0x67, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75,
	0x72, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c,
	0x74, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x63,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x69,
	0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x44, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x53,
	0x69, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x04, 0x69, 0x74,
	0x65, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76,
	0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03,
	0x65, 0x72, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x22, 0x6a,
	0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x12, 0x1d,
	0x0a, 0x0a, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a,
	0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x12, 0x1c, 0x0a, 0x09,
	0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0xef, 0x01, 0x0a, 0x0a,
	0x53, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61,
	0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x12, 0x1c, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x12,
	0x1d, 0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x6c, 0x74, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x4c, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x67, 0x74, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x47, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x69, 0x73, 0x5f, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x09, 0x69, 0x73, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x22, 0x45, 0x0a,
	0x0b, 0x53, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x12, 0x20, 0x0a, 0x04,
	0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c, 0x2e, 0x74, 0x70, 0x6c,
	0x73, 0x76, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x52, 0x04, 0x6c, 0x69, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74,
	0x6f, 0x74, 0x61, 0x6c, 0x22, 0x0e, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69,
	0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x22, 0x0f, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0xd2, 0x02, 0x0a, 0x03, 0x52, 0x65, 0x63, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16,
	0x0a, 0x06, 0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x6d, 0x6f, 0x62, 0x69, 0x6c, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6e, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x61, 0x70, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x23, 0x0a,
	0x0d, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x74, 0x65, 0x6d, 0x70, 0x6c, 0x61, 0x74, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x15, 0x0a, 0x06, 0x74, 0x70, 0x6c, 0x5f, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x70, 0x6c, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x70, 0x6c,
	0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x74, 0x70,
	0x6c, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x61,
	0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x65, 0x6e, 0x64, 0x41, 0x74, 0x12,
	0x1f, 0x0a, 0x0b, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x09,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x73, 0x65, 0x6e, 0x64, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x0a, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x70, 0x12, 0x1d, 0x0a,
	0x0a, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0b, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x09, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x12, 0x1d, 0x0a, 0x0a,
	0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0x26, 0x0a, 0x0c, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x6d,
	0x6f, 0x62, 0x69, 0x6c, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x6f, 0x62,
	0x69, 0x6c, 0x65, 0x22, 0x1f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x02, 0x69, 0x64, 0x22, 0x1f, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x42, 0x79,
	0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x43, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1f, 0x0a, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x52,
	0x65, 0x63, 0x52, 0x04, 0x69, 0x74, 0x65, 0x6d, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x72, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x65, 0x72, 0x72, 0x32, 0xa6, 0x02, 0x0a, 0x06, 0x54,
	0x70, 0x6c, 0x53, 0x76, 0x63, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x54, 0x70, 0x6c, 0x42,
	0x79, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74,
	0x54, 0x70, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x74, 0x70, 0x6c,
	0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x54, 0x70, 0x6c, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x12,
	0x14, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x54,
	0x70, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x09,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x12, 0x14, 0x2e, 0x74, 0x70, 0x6c, 0x73,
	0x76, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x71, 0x1a,
	0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54,
	0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12, 0x37, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x54, 0x70, 0x6c, 0x12, 0x14, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x71, 0x1a, 0x14, 0x2e, 0x74, 0x70, 0x6c, 0x73,
	0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x54, 0x70, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x32, 0x0a, 0x07, 0x54, 0x70, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x74, 0x70, 0x6c,
	0x73, 0x76, 0x63, 0x2e, 0x54, 0x70, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13,
	0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x54, 0x70, 0x6c, 0x4c, 0x69, 0x73, 0x74, 0x52,
	0x65, 0x73, 0x70, 0x32, 0xab, 0x02, 0x0a, 0x0a, 0x54, 0x70, 0x6c, 0x53, 0x69, 0x67, 0x6e, 0x53,
	0x76, 0x63, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x42, 0x79, 0x49, 0x64,
	0x12, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67,
	0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x16, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63,
	0x2e, 0x47, 0x65, 0x74, 0x53, 0x69, 0x67, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x12, 0x14, 0x2e, 0x74,
	0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x52,
	0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x55, 0x70, 0x64,
	0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x12, 0x14, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74,
	0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x53, 0x69, 0x67, 0x52,
	0x65, 0x73, 0x70, 0x12, 0x38, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67,
	0x12, 0x14, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x53, 0x69, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e,
	0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x53, 0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x12, 0x32, 0x0a,
	0x07, 0x53, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x12, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76,
	0x63, 0x2e, 0x53, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x1a, 0x13, 0x2e, 0x74,
	0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x53, 0x69, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73,
	0x70, 0x32, 0x83, 0x01, 0x0a, 0x0a, 0x54, 0x70, 0x6c, 0x53, 0x65, 0x6e, 0x64, 0x53, 0x76, 0x63,
	0x12, 0x38, 0x0a, 0x09, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x12, 0x14, 0x2e,
	0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x63,
	0x52, 0x65, 0x71, 0x1a, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3b, 0x0a, 0x0a, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x63, 0x42, 0x79, 0x49, 0x64, 0x12, 0x15, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76,
	0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x42, 0x79, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a,
	0x16, 0x2e, 0x74, 0x70, 0x6c, 0x73, 0x76, 0x63, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x63, 0x42,
	0x79, 0x49, 0x64, 0x52, 0x65, 0x73, 0x70, 0x42, 0x0a, 0x5a, 0x08, 0x2e, 0x2f, 0x74, 0x70, 0x6c,
	0x73, 0x76, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_tplsvc_proto_rawDescOnce sync.Once
	file_tplsvc_proto_rawDescData = file_tplsvc_proto_rawDesc
)

func file_tplsvc_proto_rawDescGZIP() []byte {
	file_tplsvc_proto_rawDescOnce.Do(func() {
		file_tplsvc_proto_rawDescData = protoimpl.X.CompressGZIP(file_tplsvc_proto_rawDescData)
	})
	return file_tplsvc_proto_rawDescData
}

var file_tplsvc_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_tplsvc_proto_goTypes = []interface{}{
	(*Tpl)(nil),            // 0: tplsvc.Tpl
	(*GetTplByIdReq)(nil),  // 1: tplsvc.GetTplByIdReq
	(*GetTplByIdResp)(nil), // 2: tplsvc.GetTplByIdResp
	(*CreateTplReq)(nil),   // 3: tplsvc.CreateTplReq
	(*CreateTplResp)(nil),  // 4: tplsvc.CreateTplResp
	(*TplListReq)(nil),     // 5: tplsvc.TplListReq
	(*TplListResp)(nil),    // 6: tplsvc.TplListResp
	(*UpdateTplReq)(nil),   // 7: tplsvc.UpdateTplReq
	(*UpdateTplResp)(nil),  // 8: tplsvc.UpdateTplResp
	(*DeleteTplReq)(nil),   // 9: tplsvc.DeleteTplReq
	(*DeletTplResp)(nil),   // 10: tplsvc.DeletTplResp
	(*Sign)(nil),           // 11: tplsvc.Sign
	(*GetSigByIdReq)(nil),  // 12: tplsvc.GetSigByIdReq
	(*GetSigByIdResp)(nil), // 13: tplsvc.GetSigByIdResp
	(*CreateSigReq)(nil),   // 14: tplsvc.CreateSigReq
	(*CreateSigResp)(nil),  // 15: tplsvc.CreateSigResp
	(*SigListReq)(nil),     // 16: tplsvc.SigListReq
	(*SigListResp)(nil),    // 17: tplsvc.SigListResp
	(*UpdateSigReq)(nil),   // 18: tplsvc.UpdateSigReq
	(*UpdateSigResp)(nil),  // 19: tplsvc.UpdateSigResp
	(*DeleteSigReq)(nil),   // 20: tplsvc.DeleteSigReq
	(*DeleteSigResp)(nil),  // 21: tplsvc.DeleteSigResp
	(*Rec)(nil),            // 22: tplsvc.Rec
	(*CreateRecReq)(nil),   // 23: tplsvc.CreateRecReq
	(*CreateRecResp)(nil),  // 24: tplsvc.CreateRecResp
	(*GetRecByIdReq)(nil),  // 25: tplsvc.GetRecByIdReq
	(*GetRecByIdResp)(nil), // 26: tplsvc.GetRecByIdResp
}
var file_tplsvc_proto_depIdxs = []int32{
	0,  // 0: tplsvc.GetTplByIdResp.item:type_name -> tplsvc.Tpl
	0,  // 1: tplsvc.TplListResp.list:type_name -> tplsvc.Tpl
	11, // 2: tplsvc.GetSigByIdResp.item:type_name -> tplsvc.Sign
	11, // 3: tplsvc.SigListResp.list:type_name -> tplsvc.Sign
	22, // 4: tplsvc.GetRecByIdResp.item:type_name -> tplsvc.Rec
	1,  // 5: tplsvc.TplSvc.GetTplById:input_type -> tplsvc.GetTplByIdReq
	3,  // 6: tplsvc.TplSvc.CreateTpl:input_type -> tplsvc.CreateTplReq
	7,  // 7: tplsvc.TplSvc.UpdateTpl:input_type -> tplsvc.UpdateTplReq
	9,  // 8: tplsvc.TplSvc.DeleteTpl:input_type -> tplsvc.DeleteTplReq
	5,  // 9: tplsvc.TplSvc.TplList:input_type -> tplsvc.TplListReq
	12, // 10: tplsvc.TplSignSvc.GetSigById:input_type -> tplsvc.GetSigByIdReq
	14, // 11: tplsvc.TplSignSvc.CreateSig:input_type -> tplsvc.CreateSigReq
	18, // 12: tplsvc.TplSignSvc.UpdateSig:input_type -> tplsvc.UpdateSigReq
	20, // 13: tplsvc.TplSignSvc.DeleteSig:input_type -> tplsvc.DeleteSigReq
	16, // 14: tplsvc.TplSignSvc.SigList:input_type -> tplsvc.SigListReq
	23, // 15: tplsvc.TplSendSvc.CreateRec:input_type -> tplsvc.CreateRecReq
	25, // 16: tplsvc.TplSendSvc.GetRecById:input_type -> tplsvc.GetRecByIdReq
	2,  // 17: tplsvc.TplSvc.GetTplById:output_type -> tplsvc.GetTplByIdResp
	4,  // 18: tplsvc.TplSvc.CreateTpl:output_type -> tplsvc.CreateTplResp
	8,  // 19: tplsvc.TplSvc.UpdateTpl:output_type -> tplsvc.UpdateTplResp
	10, // 20: tplsvc.TplSvc.DeleteTpl:output_type -> tplsvc.DeletTplResp
	6,  // 21: tplsvc.TplSvc.TplList:output_type -> tplsvc.TplListResp
	13, // 22: tplsvc.TplSignSvc.GetSigById:output_type -> tplsvc.GetSigByIdResp
	15, // 23: tplsvc.TplSignSvc.CreateSig:output_type -> tplsvc.CreateSigResp
	19, // 24: tplsvc.TplSignSvc.UpdateSig:output_type -> tplsvc.UpdateSigResp
	21, // 25: tplsvc.TplSignSvc.DeleteSig:output_type -> tplsvc.DeleteSigResp
	17, // 26: tplsvc.TplSignSvc.SigList:output_type -> tplsvc.SigListResp
	24, // 27: tplsvc.TplSendSvc.CreateRec:output_type -> tplsvc.CreateRecResp
	26, // 28: tplsvc.TplSendSvc.GetRecById:output_type -> tplsvc.GetRecByIdResp
	17, // [17:29] is the sub-list for method output_type
	5,  // [5:17] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_tplsvc_proto_init() }
func file_tplsvc_proto_init() {
	if File_tplsvc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_tplsvc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Tpl); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTplByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetTplByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTplReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateTplResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TplListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TplListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTplReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateTplResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteTplReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletTplResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Sign); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSigByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSigByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateSigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigListReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SigListResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateSigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSigReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteSigResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Rec); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateRecResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecByIdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_tplsvc_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetRecByIdResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_tplsvc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_tplsvc_proto_goTypes,
		DependencyIndexes: file_tplsvc_proto_depIdxs,
		MessageInfos:      file_tplsvc_proto_msgTypes,
	}.Build()
	File_tplsvc_proto = out.File
	file_tplsvc_proto_rawDesc = nil
	file_tplsvc_proto_goTypes = nil
	file_tplsvc_proto_depIdxs = nil
}
