// Code generated by goctl. DO NOT EDIT.
// Source: tplsvc.proto

package tplsvc

import (
	"context"

	"github.com/aheadIV/NightVoyager/tplsvc/types/tplsvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRecReq   = tplsvc.CreateRecReq
	CreateRecResp  = tplsvc.CreateRecResp
	CreateSigReq   = tplsvc.CreateSigReq
	CreateSigResp  = tplsvc.CreateSigResp
	CreateTplReq   = tplsvc.CreateTplReq
	CreateTplResp  = tplsvc.CreateTplResp
	DeletTplResp   = tplsvc.DeletTplResp
	DeleteSigReq   = tplsvc.DeleteSigReq
	DeleteSigResp  = tplsvc.DeleteSigResp
	DeleteTplReq   = tplsvc.DeleteTplReq
	GetRecByIdReq  = tplsvc.GetRecByIdReq
	GetRecByIdResp = tplsvc.GetRecByIdResp
	GetSigByIdReq  = tplsvc.GetSigByIdReq
	GetSigByIdResp = tplsvc.GetSigByIdResp
	GetTplByIdReq  = tplsvc.GetTplByIdReq
	GetTplByIdResp = tplsvc.GetTplByIdResp
	Rec            = tplsvc.Rec
	SigListReq     = tplsvc.SigListReq
	SigListResp    = tplsvc.SigListResp
	Sign           = tplsvc.Sign
	Tpl            = tplsvc.Tpl
	TplListReq     = tplsvc.TplListReq
	TplListResp    = tplsvc.TplListResp
	UpdateSigReq   = tplsvc.UpdateSigReq
	UpdateSigResp  = tplsvc.UpdateSigResp
	UpdateTplReq   = tplsvc.UpdateTplReq
	UpdateTplResp  = tplsvc.UpdateTplResp

	TplSvc interface {
		GetTplById(ctx context.Context, in *GetTplByIdReq, opts ...grpc.CallOption) (*GetTplByIdResp, error)
		CreateTpl(ctx context.Context, in *CreateTplReq, opts ...grpc.CallOption) (*CreateTplResp, error)
		UpdateTpl(ctx context.Context, in *UpdateTplReq, opts ...grpc.CallOption) (*UpdateTplResp, error)
		DeleteTpl(ctx context.Context, in *DeleteTplReq, opts ...grpc.CallOption) (*DeletTplResp, error)
		TplList(ctx context.Context, in *TplListReq, opts ...grpc.CallOption) (*TplListResp, error)
	}

	defaultTplSvc struct {
		cli zrpc.Client
	}
)

func NewTplSvc(cli zrpc.Client) TplSvc {
	return &defaultTplSvc{
		cli: cli,
	}
}

func (m *defaultTplSvc) GetTplById(ctx context.Context, in *GetTplByIdReq, opts ...grpc.CallOption) (*GetTplByIdResp, error) {
	client := tplsvc.NewTplSvcClient(m.cli.Conn())
	return client.GetTplById(ctx, in, opts...)
}

func (m *defaultTplSvc) CreateTpl(ctx context.Context, in *CreateTplReq, opts ...grpc.CallOption) (*CreateTplResp, error) {
	client := tplsvc.NewTplSvcClient(m.cli.Conn())
	return client.CreateTpl(ctx, in, opts...)
}

func (m *defaultTplSvc) UpdateTpl(ctx context.Context, in *UpdateTplReq, opts ...grpc.CallOption) (*UpdateTplResp, error) {
	client := tplsvc.NewTplSvcClient(m.cli.Conn())
	return client.UpdateTpl(ctx, in, opts...)
}

func (m *defaultTplSvc) DeleteTpl(ctx context.Context, in *DeleteTplReq, opts ...grpc.CallOption) (*DeletTplResp, error) {
	client := tplsvc.NewTplSvcClient(m.cli.Conn())
	return client.DeleteTpl(ctx, in, opts...)
}

func (m *defaultTplSvc) TplList(ctx context.Context, in *TplListReq, opts ...grpc.CallOption) (*TplListResp, error) {
	client := tplsvc.NewTplSvcClient(m.cli.Conn())
	return client.TplList(ctx, in, opts...)
}
