// Code generated by goctl. DO NOT EDIT.
// Source: sendsvc.proto

package tplsignsvc

import (
	"context"

	"github.com/aheadIV/NightVoyager/sendsvc/types/sendsvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRecReq   = sendsvc.CreateRecReq
	CreateRecResp  = sendsvc.CreateRecResp
	CreateSigReq   = sendsvc.CreateSigReq
	CreateSigResp  = sendsvc.CreateSigResp
	CreateTplReq   = sendsvc.CreateTplReq
	CreateTplResp  = sendsvc.CreateTplResp
	DeletTplResp   = sendsvc.DeletTplResp
	DeleteSigReq   = sendsvc.DeleteSigReq
	DeleteSigResp  = sendsvc.DeleteSigResp
	DeleteTplReq   = sendsvc.DeleteTplReq
	GetRecByIdReq  = sendsvc.GetRecByIdReq
	GetRecByIdResp = sendsvc.GetRecByIdResp
	GetSigByIdReq  = sendsvc.GetSigByIdReq
	GetSigByIdResp = sendsvc.GetSigByIdResp
	GetTplByIdReq  = sendsvc.GetTplByIdReq
	GetTplByIdResp = sendsvc.GetTplByIdResp
	Rec            = sendsvc.Rec
	SigListReq     = sendsvc.SigListReq
	SigListResp    = sendsvc.SigListResp
	Sign           = sendsvc.Sign
	Tpl            = sendsvc.Tpl
	TplListReq     = sendsvc.TplListReq
	TplListResp    = sendsvc.TplListResp
	UpdateSigReq   = sendsvc.UpdateSigReq
	UpdateSigResp  = sendsvc.UpdateSigResp
	UpdateTplReq   = sendsvc.UpdateTplReq
	UpdateTplResp  = sendsvc.UpdateTplResp

	TplSignSvc interface {
		GetSigById(ctx context.Context, in *GetSigByIdReq, opts ...grpc.CallOption) (*GetSigByIdResp, error)
		CreateSig(ctx context.Context, in *CreateSigReq, opts ...grpc.CallOption) (*CreateSigResp, error)
		UpdateSig(ctx context.Context, in *UpdateSigReq, opts ...grpc.CallOption) (*UpdateSigResp, error)
		DeleteSig(ctx context.Context, in *DeleteSigReq, opts ...grpc.CallOption) (*DeleteSigResp, error)
		SigList(ctx context.Context, in *SigListReq, opts ...grpc.CallOption) (*SigListResp, error)
	}

	defaultTplSignSvc struct {
		cli zrpc.Client
	}
)

func NewTplSignSvc(cli zrpc.Client) TplSignSvc {
	return &defaultTplSignSvc{
		cli: cli,
	}
}

func (m *defaultTplSignSvc) GetSigById(ctx context.Context, in *GetSigByIdReq, opts ...grpc.CallOption) (*GetSigByIdResp, error) {
	client := sendsvc.NewTplSignSvcClient(m.cli.Conn())
	return client.GetSigById(ctx, in, opts...)
}

func (m *defaultTplSignSvc) CreateSig(ctx context.Context, in *CreateSigReq, opts ...grpc.CallOption) (*CreateSigResp, error) {
	client := sendsvc.NewTplSignSvcClient(m.cli.Conn())
	return client.CreateSig(ctx, in, opts...)
}

func (m *defaultTplSignSvc) UpdateSig(ctx context.Context, in *UpdateSigReq, opts ...grpc.CallOption) (*UpdateSigResp, error) {
	client := sendsvc.NewTplSignSvcClient(m.cli.Conn())
	return client.UpdateSig(ctx, in, opts...)
}

func (m *defaultTplSignSvc) DeleteSig(ctx context.Context, in *DeleteSigReq, opts ...grpc.CallOption) (*DeleteSigResp, error) {
	client := sendsvc.NewTplSignSvcClient(m.cli.Conn())
	return client.DeleteSig(ctx, in, opts...)
}

func (m *defaultTplSignSvc) SigList(ctx context.Context, in *SigListReq, opts ...grpc.CallOption) (*SigListResp, error) {
	client := sendsvc.NewTplSignSvcClient(m.cli.Conn())
	return client.SigList(ctx, in, opts...)
}
