// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: addrsvc.proto

package addrsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Addrsvc_Ping_FullMethodName = "/addrsvc.Addrsvc/Ping"
)

// AddrsvcClient is the client API for Addrsvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AddrsvcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type addrsvcClient struct {
	cc grpc.ClientConnInterface
}

func NewAddrsvcClient(cc grpc.ClientConnInterface) AddrsvcClient {
	return &addrsvcClient{cc}
}

func (c *addrsvcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Addrsvc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AddrsvcServer is the server API for Addrsvc service.
// All implementations must embed UnimplementedAddrsvcServer
// for forward compatibility
type AddrsvcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedAddrsvcServer()
}

// UnimplementedAddrsvcServer must be embedded to have forward compatible implementations.
type UnimplementedAddrsvcServer struct {
}

func (UnimplementedAddrsvcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedAddrsvcServer) mustEmbedUnimplementedAddrsvcServer() {}

// UnsafeAddrsvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AddrsvcServer will
// result in compilation errors.
type UnsafeAddrsvcServer interface {
	mustEmbedUnimplementedAddrsvcServer()
}

func RegisterAddrsvcServer(s grpc.ServiceRegistrar, srv AddrsvcServer) {
	s.RegisterService(&Addrsvc_ServiceDesc, srv)
}

func _Addrsvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AddrsvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Addrsvc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AddrsvcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Addrsvc_ServiceDesc is the grpc.ServiceDesc for Addrsvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Addrsvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "addrsvc.Addrsvc",
	HandlerType: (*AddrsvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Addrsvc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "addrsvc.proto",
}
