// Code generated by goctl. DO NOT EDIT.
// Source: templatesvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/templatesvc/internal/logic"
	"github.com/aheadIV/NightVoyager/templatesvc/internal/svc"
	"github.com/aheadIV/NightVoyager/templatesvc/types/templatesvc"
)

type TemplatesvcServer struct {
	svcCtx *svc.ServiceContext
	templatesvc.UnimplementedTemplatesvcServer
}

func NewTemplatesvcServer(svcCtx *svc.ServiceContext) *TemplatesvcServer {
	return &TemplatesvcServer{
		svcCtx: svcCtx,
	}
}

func (s *TemplatesvcServer) Ping(ctx context.Context, in *templatesvc.Request) (*templatesvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
