// Code generated by goctl. DO NOT EDIT.
// Source: appsvc.proto

package appsendlogsvc

import (
	"context"

	"github.com/aheadIV/NightVoyager/appsvc/types/appsvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateAppReq   = appsvc.CreateAppReq
	CreateAppResp  = appsvc.CreateAppResp
	GetAppByIdReq  = appsvc.GetAppByIdReq
	GetAppByIdResp = appsvc.GetAppByIdResp
	Req            = appsvc.Req
	Resp           = appsvc.Resp

	AppSendLogsvc interface {
		InsertSendLog(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
		AppSendLogList(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error)
	}

	defaultAppSendLogsvc struct {
		cli zrpc.Client
	}
)

func NewAppSendLogsvc(cli zrpc.Client) AppSendLogsvc {
	return &defaultAppSendLogsvc{
		cli: cli,
	}
}

func (m *defaultAppSendLogsvc) InsertSendLog(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	client := appsvc.NewAppSendLogsvcClient(m.cli.Conn())
	return client.InsertSendLog(ctx, in, opts...)
}

func (m *defaultAppSendLogsvc) AppSendLogList(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Resp, error) {
	client := appsvc.NewAppSendLogsvcClient(m.cli.Conn())
	return client.AppSendLogList(ctx, in, opts...)
}
