// Code generated by goctl. DO NOT EDIT.
// Source: appsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/appsvc/internal/logic"
	"github.com/aheadIV/NightVoyager/appsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/appsvc/types/appsvc"
)

type AppsvcServer struct {
	svcCtx *svc.ServiceContext
	appsvc.UnimplementedAppsvcServer
}

func NewAppsvcServer(svcCtx *svc.ServiceContext) *AppsvcServer {
	return &AppsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AppsvcServer) GetApp(ctx context.Context, in *appsvc.GetAppReq) (*appsvc.GetAppResp, error) {
	l := logic.NewGetAppLogic(ctx, s.svcCtx)
	return l.GetApp(in)
}

func (s *AppsvcServer) CreateApp(ctx context.Context, in *appsvc.CreateAppReq) (*appsvc.CreateAppResp, error) {
	l := logic.NewCreateAppLogic(ctx, s.svcCtx)
	return l.CreateApp(in)
}
