// Code generated by goctl. DO NOT EDIT.
// Source: appsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/appsvc/appsvc"
	"github.com/aheadIV/NightVoyager/appsvc/internal/logic"
	"github.com/aheadIV/NightVoyager/appsvc/internal/svc"
)

type AppsvcServer struct {
	svcCtx *svc.ServiceContext
	appsvc.UnimplementedAppsvcServer
}

func NewAppsvcServer(svcCtx *svc.ServiceContext) *AppsvcServer {
	return &AppsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AppsvcServer) Ping(ctx context.Context, in *appsvc.Request) (*appsvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}

func (s *AppsvcServer) GetApp(ctx context.Context, in *appsvc.GetAppReq) (*appsvc.GetAppResp, error) {
	l := logic.NewGetAppLogic(ctx, s.svcCtx)
	return l.GetApp(in)
}
