// Code generated by goctl. DO NOT EDIT.
// Source: appsvc.proto

package appsvcclient

import (
	"context"

	"github.com/aheadIV/NightVoyager/appsvc/appsvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	GetAppReq  = appsvc.GetAppReq
	GetAppResp = appsvc.GetAppResp
	Request    = appsvc.Request
	Response   = appsvc.Response

	Appsvc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
		GetApp(ctx context.Context, in *GetAppReq, opts ...grpc.CallOption) (*GetAppResp, error)
	}

	defaultAppsvc struct {
		cli zrpc.Client
	}
)

func NewAppsvc(cli zrpc.Client) Appsvc {
	return &defaultAppsvc{
		cli: cli,
	}
}

func (m *defaultAppsvc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := appsvc.NewAppsvcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}

func (m *defaultAppsvc) GetApp(ctx context.Context, in *GetAppReq, opts ...grpc.CallOption) (*GetAppResp, error) {
	client := appsvc.NewAppsvcClient(m.cli.Conn())
	return client.GetApp(ctx, in, opts...)
}
