// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: sigsvc.proto

package sigsvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Sigsvc_Ping_FullMethodName = "/sigsvc.Sigsvc/Ping"
)

// SigsvcClient is the client API for Sigsvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SigsvcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type sigsvcClient struct {
	cc grpc.ClientConnInterface
}

func NewSigsvcClient(cc grpc.ClientConnInterface) SigsvcClient {
	return &sigsvcClient{cc}
}

func (c *sigsvcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Sigsvc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SigsvcServer is the server API for Sigsvc service.
// All implementations must embed UnimplementedSigsvcServer
// for forward compatibility
type SigsvcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedSigsvcServer()
}

// UnimplementedSigsvcServer must be embedded to have forward compatible implementations.
type UnimplementedSigsvcServer struct {
}

func (UnimplementedSigsvcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedSigsvcServer) mustEmbedUnimplementedSigsvcServer() {}

// UnsafeSigsvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SigsvcServer will
// result in compilation errors.
type UnsafeSigsvcServer interface {
	mustEmbedUnimplementedSigsvcServer()
}

func RegisterSigsvcServer(s grpc.ServiceRegistrar, srv SigsvcServer) {
	s.RegisterService(&Sigsvc_ServiceDesc, srv)
}

func _Sigsvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SigsvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Sigsvc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SigsvcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Sigsvc_ServiceDesc is the grpc.ServiceDesc for Sigsvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Sigsvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sigsvc.Sigsvc",
	HandlerType: (*SigsvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Sigsvc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sigsvc.proto",
}
