// Code generated by goctl. DO NOT EDIT.
// Source: addrsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/addrsvc/addrsvc"
	"github.com/aheadIV/NightVoyager/addrsvc/internal/logic"
	"github.com/aheadIV/NightVoyager/addrsvc/internal/svc"
)

type AddrsvcServer struct {
	svcCtx *svc.ServiceContext
	addrsvc.UnimplementedAddrsvcServer
}

func NewAddrsvcServer(svcCtx *svc.ServiceContext) *AddrsvcServer {
	return &AddrsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AddrsvcServer) Ping(ctx context.Context, in *addrsvc.Request) (*addrsvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
