// Code generated by goctl. DO NOT EDIT.
// Source: queuesvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/queuesvc/internal/logic"
	"github.com/aheadIV/NightVoyager/queuesvc/internal/svc"
	"github.com/aheadIV/NightVoyager/queuesvc/types/queuesvc"
)

type QueuesvcServer struct {
	svcCtx *svc.ServiceContext
	queuesvc.UnimplementedQueuesvcServer
}

func NewQueuesvcServer(svcCtx *svc.ServiceContext) *QueuesvcServer {
	return &QueuesvcServer{
		svcCtx: svcCtx,
	}
}

func (s *QueuesvcServer) Ping(ctx context.Context, in *queuesvc.Request) (*queuesvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
