// Code generated by goctl. DO NOT EDIT.
// Source: tplsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/tplsvc/internal/logic"
	"github.com/aheadIV/NightVoyager/tplsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/tplsvc/types/tplsvc"
)

type TplsvcServer struct {
	svcCtx *svc.ServiceContext
	tplsvc.UnimplementedTplsvcServer
}

func NewTplsvcServer(svcCtx *svc.ServiceContext) *TplsvcServer {
	return &TplsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *TplsvcServer) Ping(ctx context.Context, in *tplsvc.Request) (*tplsvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
