// Code generated by goctl. DO NOT EDIT.
// Source: accountsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/accountsvc/internal/logic"
	"github.com/aheadIV/NightVoyager/accountsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/accountsvc/types/accountsvc"
)

type AccountsvcServer struct {
	svcCtx *svc.ServiceContext
	accountsvc.UnimplementedAccountsvcServer
}

func NewAccountsvcServer(svcCtx *svc.ServiceContext) *AccountsvcServer {
	return &AccountsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountsvcServer) GetByAccount(ctx context.Context, in *accountsvc.Request) (*accountsvc.Response, error) {
	l := logic.NewGetByAccountLogic(ctx, s.svcCtx)
	return l.GetByAccount(in)
}

func (s *AccountsvcServer) GetByID(ctx context.Context, in *accountsvc.Request) (*accountsvc.Response, error) {
	l := logic.NewGetByIDLogic(ctx, s.svcCtx)
	return l.GetByID(in)
}

func (s *AccountsvcServer) Create(ctx context.Context, in *accountsvc.Request) (*accountsvc.Response, error) {
	l := logic.NewCreateLogic(ctx, s.svcCtx)
	return l.Create(in)
}

func (s *AccountsvcServer) Update(ctx context.Context, in *accountsvc.Request) (*accountsvc.Response, error) {
	l := logic.NewUpdateLogic(ctx, s.svcCtx)
	return l.Update(in)
}

func (s *AccountsvcServer) Delete(ctx context.Context, in *accountsvc.Request) (*accountsvc.Response, error) {
	l := logic.NewDeleteLogic(ctx, s.svcCtx)
	return l.Delete(in)
}
