// Code generated by goctl. DO NOT EDIT.
// Source: sendsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/sendsvc/internal/logic/tplsendsvc"
	"github.com/aheadIV/NightVoyager/sendsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/sendsvc/types/sendsvc"
)

type TplSendSvcServer struct {
	svcCtx *svc.ServiceContext
	sendsvc.UnimplementedTplSendSvcServer
}

func NewTplSendSvcServer(svcCtx *svc.ServiceContext) *TplSendSvcServer {
	return &TplSendSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *TplSendSvcServer) CreateRec(ctx context.Context, in *sendsvc.CreateRecReq) (*sendsvc.CreateRecResp, error) {
	l := tplsendsvclogic.NewCreateRecLogic(ctx, s.svcCtx)
	return l.CreateRec(in)
}

func (s *TplSendSvcServer) GetRecById(ctx context.Context, in *sendsvc.GetRecByIdReq) (*sendsvc.GetRecByIdResp, error) {
	l := tplsendsvclogic.NewGetRecByIdLogic(ctx, s.svcCtx)
	return l.GetRecById(in)
}
