// Code generated by goctl. DO NOT EDIT.
// Source: tplsvc.proto

package tplsendsvc

import (
	"context"

	"github.com/aheadIV/NightVoyager/tplsvc/types/tplsvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	CreateRecReq   = tplsvc.CreateRecReq
	CreateRecResp  = tplsvc.CreateRecResp
	CreateSigReq   = tplsvc.CreateSigReq
	CreateSigResp  = tplsvc.CreateSigResp
	CreateTplReq   = tplsvc.CreateTplReq
	CreateTplResp  = tplsvc.CreateTplResp
	DeletTplResp   = tplsvc.DeletTplResp
	DeleteSigReq   = tplsvc.DeleteSigReq
	DeleteSigResp  = tplsvc.DeleteSigResp
	DeleteTplReq   = tplsvc.DeleteTplReq
	GetRecByIdReq  = tplsvc.GetRecByIdReq
	GetRecByIdResp = tplsvc.GetRecByIdResp
	GetSigByIdReq  = tplsvc.GetSigByIdReq
	GetSigByIdResp = tplsvc.GetSigByIdResp
	GetTplByIdReq  = tplsvc.GetTplByIdReq
	GetTplByIdResp = tplsvc.GetTplByIdResp
	Rec            = tplsvc.Rec
	SigListReq     = tplsvc.SigListReq
	SigListResp    = tplsvc.SigListResp
	Sign           = tplsvc.Sign
	Tpl            = tplsvc.Tpl
	TplListReq     = tplsvc.TplListReq
	TplListResp    = tplsvc.TplListResp
	UpdateSigReq   = tplsvc.UpdateSigReq
	UpdateSigResp  = tplsvc.UpdateSigResp
	UpdateTplReq   = tplsvc.UpdateTplReq
	UpdateTplResp  = tplsvc.UpdateTplResp

	TplSendSvc interface {
		CreateRec(ctx context.Context, in *CreateRecReq, opts ...grpc.CallOption) (*CreateRecResp, error)
		GetRecById(ctx context.Context, in *GetRecByIdReq, opts ...grpc.CallOption) (*GetRecByIdResp, error)
	}

	defaultTplSendSvc struct {
		cli zrpc.Client
	}
)

func NewTplSendSvc(cli zrpc.Client) TplSendSvc {
	return &defaultTplSendSvc{
		cli: cli,
	}
}

func (m *defaultTplSendSvc) CreateRec(ctx context.Context, in *CreateRecReq, opts ...grpc.CallOption) (*CreateRecResp, error) {
	client := tplsvc.NewTplSendSvcClient(m.cli.Conn())
	return client.CreateRec(ctx, in, opts...)
}

func (m *defaultTplSendSvc) GetRecById(ctx context.Context, in *GetRecByIdReq, opts ...grpc.CallOption) (*GetRecByIdResp, error) {
	client := tplsvc.NewTplSendSvcClient(m.cli.Conn())
	return client.GetRecById(ctx, in, opts...)
}
