// Code generated by goctl. DO NOT EDIT.
// Source: sigsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/sigsvc/internal/logic"
	"github.com/aheadIV/NightVoyager/sigsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/sigsvc/sigsvc"
)

type SigsvcServer struct {
	svcCtx *svc.ServiceContext
	sigsvc.UnimplementedSigsvcServer
}

func NewSigsvcServer(svcCtx *svc.ServiceContext) *SigsvcServer {
	return &SigsvcServer{
		svcCtx: svcCtx,
	}
}

func (s *SigsvcServer) Ping(ctx context.Context, in *sigsvc.Request) (*sigsvc.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
