// Code generated by goctl. DO NOT EDIT.
// Source: sendsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/sendsvc/internal/logic/tplsvc"
	"github.com/aheadIV/NightVoyager/sendsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/sendsvc/types/sendsvc"
)

type TplSvcServer struct {
	svcCtx *svc.ServiceContext
	sendsvc.UnimplementedTplSvcServer
}

func NewTplSvcServer(svcCtx *svc.ServiceContext) *TplSvcServer {
	return &TplSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *TplSvcServer) GetTplById(ctx context.Context, in *sendsvc.GetTplByIdReq) (*sendsvc.GetTplByIdResp, error) {
	l := tplsvclogic.NewGetTplByIdLogic(ctx, s.svcCtx)
	return l.GetTplById(in)
}

func (s *TplSvcServer) CreateTpl(ctx context.Context, in *sendsvc.CreateTplReq) (*sendsvc.CreateTplResp, error) {
	l := tplsvclogic.NewCreateTplLogic(ctx, s.svcCtx)
	return l.CreateTpl(in)
}

func (s *TplSvcServer) UpdateTpl(ctx context.Context, in *sendsvc.UpdateTplReq) (*sendsvc.UpdateTplResp, error) {
	l := tplsvclogic.NewUpdateTplLogic(ctx, s.svcCtx)
	return l.UpdateTpl(in)
}

func (s *TplSvcServer) DeleteTpl(ctx context.Context, in *sendsvc.DeleteTplReq) (*sendsvc.DeletTplResp, error) {
	l := tplsvclogic.NewDeleteTplLogic(ctx, s.svcCtx)
	return l.DeleteTpl(in)
}

func (s *TplSvcServer) TplList(ctx context.Context, in *sendsvc.TplListReq) (*sendsvc.TplListResp, error) {
	l := tplsvclogic.NewTplListLogic(ctx, s.svcCtx)
	return l.TplList(in)
}
