// Code generated by goctl. DO NOT EDIT.
// Source: accountsvc.proto

package server

import (
	"context"

	"github.com/aheadIV/NightVoyager/accountsvc/internal/logic/accountlogsvc"
	"github.com/aheadIV/NightVoyager/accountsvc/internal/svc"
	"github.com/aheadIV/NightVoyager/accountsvc/types/accountsvc"
)

type AccountLogSvcServer struct {
	svcCtx *svc.ServiceContext
	accountsvc.UnimplementedAccountLogSvcServer
}

func NewAccountLogSvcServer(svcCtx *svc.ServiceContext) *AccountLogSvcServer {
	return &AccountLogSvcServer{
		svcCtx: svcCtx,
	}
}

func (s *AccountLogSvcServer) InsertLog(ctx context.Context, in *accountsvc.InsertLogReq) (*accountsvc.InsertLogResp, error) {
	l := accountlogsvclogic.NewInsertLogLogic(ctx, s.svcCtx)
	return l.InsertLog(in)
}

func (s *AccountLogSvcServer) AccountLogList(ctx context.Context, in *accountsvc.AccountLogListReq) (*accountsvc.AccountLogListResp, error) {
	l := accountlogsvclogic.NewAccountLogListLogic(ctx, s.svcCtx)
	return l.AccountLogList(in)
}
