// Code generated by goctl. DO NOT EDIT.
package types

type RegReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type RegResp struct {
	Result string `json:"result"`
}

type LogReq struct {
	Account  string `json:"account"`
	Password string `json:"password"`
}

type LogResp struct {
	Token string `json:"token"`
}

type App struct {
	Id   int64  `path:"id"`
	Name string `json:"name"`
	Age  int    `json:"age"`
}

type AppAddReq struct {
}

type AppAddResp struct {
	AppID  int64  `json:"appid"`
	Secret string `json:"secret"`
}

type AppUdReq struct {
}

type AppUdResp struct {
}

type AppDelReq struct {
}

type AppDelResp struct {
}

type AppInfoReq struct {
}

type AppInfoResp struct {
	Data App `json:"data"`
}

type AppLsReq struct {
}

type AppLsResp struct {
	List []App `json:"list"`
}

type TplAddReq struct {
}

type TplAddResp struct {
}

type TplDelReq struct {
}

type TplDelResp struct {
}

type TplUdReq struct {
}

type TplUdResp struct {
}

type TplInfoReq struct {
}

type TplInfoResp struct {
}

type TplLsReq struct {
}

type TplLsResp struct {
}

type SigAddReq struct {
}

type SigAddResp struct {
}

type SigDelReq struct {
}

type SigDelResp struct {
}

type SigUdReq struct {
}

type SigUdResp struct {
}

type SigInfoReq struct {
}

type SigInfoResp struct {
}

type SigLsReq struct {
}

type SigLsResp struct {
}

type AddrAddReq struct {
}

type AddrAddResp struct {
}

type AddrDelReq struct {
}

type AddrDelResp struct {
}

type AddrUdReq struct {
}

type AddrUdResp struct {
}

type AddrInfoReq struct {
}

type AddrInfoResp struct {
}

type AddrLsReq struct {
}

type AddrLsResp struct {
}
