// Code generated by goctl. DO NOT EDIT.
// Source: templatesvc.proto

package templatesvcclient

import (
	"context"

	"github.com/aheadIV/NightVoyager/templatesvc/types/templatesvc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Request  = templatesvc.Request
	Response = templatesvc.Response

	Templatesvc interface {
		Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
	}

	defaultTemplatesvc struct {
		cli zrpc.Client
	}
)

func NewTemplatesvc(cli zrpc.Client) Templatesvc {
	return &defaultTemplatesvc{
		cli: cli,
	}
}

func (m *defaultTemplatesvc) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	client := templatesvc.NewTemplatesvcClient(m.cli.Conn())
	return client.Ping(ctx, in, opts...)
}
