// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: queuesvc.proto

package queuesvc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Queuesvc_Ping_FullMethodName = "/queuesvc.Queuesvc/Ping"
)

// QueuesvcClient is the client API for Queuesvc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueuesvcClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type queuesvcClient struct {
	cc grpc.ClientConnInterface
}

func NewQueuesvcClient(cc grpc.ClientConnInterface) QueuesvcClient {
	return &queuesvcClient{cc}
}

func (c *queuesvcClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, Queuesvc_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueuesvcServer is the server API for Queuesvc service.
// All implementations must embed UnimplementedQueuesvcServer
// for forward compatibility
type QueuesvcServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedQueuesvcServer()
}

// UnimplementedQueuesvcServer must be embedded to have forward compatible implementations.
type UnimplementedQueuesvcServer struct {
}

func (UnimplementedQueuesvcServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedQueuesvcServer) mustEmbedUnimplementedQueuesvcServer() {}

// UnsafeQueuesvcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueuesvcServer will
// result in compilation errors.
type UnsafeQueuesvcServer interface {
	mustEmbedUnimplementedQueuesvcServer()
}

func RegisterQueuesvcServer(s grpc.ServiceRegistrar, srv QueuesvcServer) {
	s.RegisterService(&Queuesvc_ServiceDesc, srv)
}

func _Queuesvc_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueuesvcServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Queuesvc_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueuesvcServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// Queuesvc_ServiceDesc is the grpc.ServiceDesc for Queuesvc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Queuesvc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "queuesvc.Queuesvc",
	HandlerType: (*QueuesvcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _Queuesvc_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "queuesvc.proto",
}
