name: Build and Push Docker Image

on:
  push:
    branches:
    - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GHCR
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Copy app.yaml to build context
      run: cp -r ./ ${{ github.workspace }}

    - name: Build and Push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./accountsvc/Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/accountsvc:${{ github.sha }}
